server:
  port: 8082
spring:
  application:
    name: app-order

eureka:
  client:
    service-url:
      defaultZone: http://wxd:123456@localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
feign:
  hystrix:
    enabled: true

jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
  username: root
  password: wxd21020






